#+TITLE: Statistical models of biochemical thermodynamics

This repository contains code and data for inferring the thermodynamic
properties biochemical reactions from experiments.


* Big picture
The aim is to predict the amount of energy stored or released by some
biochemical reactions (i.e. their Gibbs free energy of reaction or \Delta_rG)
based on measurements. 

Noor et al. (2013) explain how, by exploiting structural information, it is
possible to make reliable predictions of \Delta_rG values for reactions that
haven't been directly measured.

This project aims to build on Noor et al.'s work by using Bayesian
inference.

* Running the model
The modelling is done through the following python scripts:

- ~fetch_data.py~ fetches input data and writes it to the ~data~ directory
- ~prepare_data.py~ reads files from the ~data~ directory and writes a ~.json~
  file that can be used as an input for cmdstanpy.
- ~sample.py~ reads ~json~ files (data and optionally initial parameter values)
  runs ~cmdstanpy.CmdStanModel~'s ~sample~ method, runs diagnostics on the
  output and writes some csv files.

I've been using python 3.7.2 - everything will probably work for later versions
but maybe not older ones.

Python package dependencies:
- cmdstanpy
- pandas
- numpy
- quilt
- component-contribution


* A bit more detail about thermodynamics
It is possible to predict unmeasured reactions due to the following two helpful
principles.

The first, which follows from thermodynamic principles, is that the Gibbs free
energy of any reaction is related to the formation energies (i.e. the energy
stored or released by creating the compounds out of elements) of its products
and substrates:

\Delta_rG = \sum_{products}\Delta_fG \div \sum_{substrates} \Delta_fG

The second helpful principle is called group additivity. It says that the
formation energy of a compound that is composed of chemical groups is
approximately the sum of the formation energies of those components. I.e.

\Delta_fG \approx \sum_{groups}\Delta_gG 


* Statistical model

Measurements of standard delta g of reaction are modelled as depending on
compound formation energies via the following regression model:

\Delta_rG_{obs} \sim N(\Delta_rG[measurement index], \sigma)

\Delta_rG = S^{T}\Delta_fG

where
- S is a stoichiometric matrix with rows representing compounds and
columns representing reactions
- \Delta_fG is a vector of model parameters representing the unknown Gibbs
  free energy of formation for each compound.
- \Delta_rG_{obs} is a vector representing standard-condition measurements of
  Gibbs free energy of reaction for reactions in S (not necessarily every
  reaction).
- \sigma is a model parameter representing the unknown accuracy of the
  measurements.
- [measurement index] maps reactions' positions in \Delta_rG to
  their positions in \Delta_rG_{obs}.
  
The group additivity principle is incorporated with the following prior
distribution for compound formation energies:

\Delta_fG &\sim N(*G*\Delta_gG, \tau)

where
- *G* is group incidence matrix specifying how compounds decompose
  into groups.
- \Delta_gG is a vector of of model parameters representing unknown group
  formation energies.
- tau is a model parameter representing the unknown extent to which compound
  formation energies tend to deviate from the group additivity prediction.
  

* Input
The input is follows:
- A stoichiometric matrix (e.g. ~data/stoichiometry.csv~) specifying the
  reactions and compounds of interest and indicating which reactions consume
  and produce which compounds.
- A group incidence matrix (e.g. ~data/group_incidence.csv~) indicating how
  each compound decomposes into chemical groups.
- A table of measurements (e.g. ~measurements.csv~) indicating the reaction
  measured and the measured value of standard-condition delta g of reaction. In
  future I aim to also take into account experimental conditions and method, so
  these should also ideally be specified.

The script ~fetch_data.py~ gets all these things from the same source as Noor
et al using their fantastic quilt data.

* References
- Noor, E., Haraldsd\'ottir, Hulda S., Milo, R., & Fleming,
  R. M. T. (2013). Consistent Estimation of Gibbs Energy Using Component
  Contributions. PLoS Computational Biology,
  9(7), 1003098. http://dx.doi.org/10.1371/journal.pcbi.1003098
